{% set name = "local-migrator" %}
{% set version = "0.1.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/local_migrator-{{ version }}.tar.gz
  sha256: cef29852306ebb6c38a09b9cea0d0c5a2105b2f984184b9380646ff3cc829625

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - packaging

test:
  imports:
    - local_migrator
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/local-migrator/
  summary: Package for simplify data structures migrations
  license: MIT
  license_file: LICENSE.txt
  dev_url: https://github.com/Czaki/local_migrator/

extra:
  recipe-maintainers:
    - Czaki
